name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]
jobs:
  avoid_reduncy:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  build:
    runs-on: ubuntu-18.04
    needs: [avoid_reduncy]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: "16"
      - name: Install dependencies
        run: npm install
      - name: Generate build
        run: npm run build
  run_e2e_tests:
    timeout-minutes: 60
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: "16"
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
